/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelsIndexRouteImport } from './routes/hotels.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels.$hotelId'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard.favorites'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as BookingRoomIdRouteImport } from './routes/booking.$roomId'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminHotelsRouteImport } from './routes/admin.hotels'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/dashboard/favorites',
  path: '/dashboard/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/dashboard/bookings',
  path: '/dashboard/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoomIdRoute = BookingRoomIdRouteImport.update({
  id: '/booking/$roomId',
  path: '/booking/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHotelsRoute = AdminHotelsRouteImport.update({
  id: '/admin/hotels',
  path: '/admin/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/booking/$roomId': typeof BookingRoomIdRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/admin/': typeof AdminIndexRoute
  '/hotels/': typeof HotelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/booking/$roomId': typeof BookingRoomIdRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/admin': typeof AdminIndexRoute
  '/hotels': typeof HotelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/booking/$roomId': typeof BookingRoomIdRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/admin/': typeof AdminIndexRoute
  '/hotels/': typeof HotelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/admin/bookings'
    | '/admin/hotels'
    | '/admin/rooms'
    | '/auth/login'
    | '/auth/register'
    | '/booking/$roomId'
    | '/dashboard/bookings'
    | '/dashboard/favorites'
    | '/dashboard/profile'
    | '/hotels/$hotelId'
    | '/admin/'
    | '/hotels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/admin/bookings'
    | '/admin/hotels'
    | '/admin/rooms'
    | '/auth/login'
    | '/auth/register'
    | '/booking/$roomId'
    | '/dashboard/bookings'
    | '/dashboard/favorites'
    | '/dashboard/profile'
    | '/hotels/$hotelId'
    | '/admin'
    | '/hotels'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/admin/bookings'
    | '/admin/hotels'
    | '/admin/rooms'
    | '/auth/login'
    | '/auth/register'
    | '/booking/$roomId'
    | '/dashboard/bookings'
    | '/dashboard/favorites'
    | '/dashboard/profile'
    | '/hotels/$hotelId'
    | '/admin/'
    | '/hotels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminHotelsRoute: typeof AdminHotelsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BookingRoomIdRoute: typeof BookingRoomIdRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/dashboard/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/dashboard/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$roomId': {
      id: '/booking/$roomId'
      path: '/booking/$roomId'
      fullPath: '/booking/$roomId'
      preLoaderRoute: typeof BookingRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hotels': {
      id: '/admin/hotels'
      path: '/admin/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AdminHotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminHotelsRoute: AdminHotelsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BookingRoomIdRoute: BookingRoomIdRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  HotelsHotelIdRoute: HotelsHotelIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  HotelsIndexRoute: HotelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
